@startuml
' ========================================
' start: configuration
' ========================================

skinparam linetype ortho

' ========================================
' end: configuration
' ========================================

' ========================================
' start: definition of entities/classes
' ========================================

class Component {
  code : CodeableConcept [1..1] « LOINCCodes?? »
  value[x] : Type [0..1] « Quantity|CodeableConcept|string|boolean|integer|Range|Ratio|SampledData|time|dateTime|Period »
  dataAbsentReason : CodeableConcept [0..1] « DataAbsentReason+ »
  interpretation : CodeableConcept [0..*] « ObservationInterpretationCodes+ »
}

class Encounter {
}

class Observation {
  identifier : Identifier [0..*]
  category : CodeableConcept [0..*]
  code : CodeableConcept [1..1]
  ...
}

class Patient {
}

class ReferenceRange {
  low : Quantity(SimpleQuantity) [0..1]
  high : Quantity(SimpleQuantity) [0..1]
  type : CodeableConcept [0..1] « ObservationReferenceRangeMean...? »
  appliesTo : CodeableConcept [0..*] « ObservationReferenceRangeAppl...?? »
  age : Range [0..1]
  text : string [0..1]
}

' ========================================
' end: definition of entities/classes
' ========================================

' ========================================
' start: definition of associations
' ========================================

Observation *-- "[0..*]" Component : component
Observation *-- "[0..*]" ReferenceRange : referenceRange
Component *-- "[0..*]" ReferenceRange : referenceRange
Observation *-- "[0..1]" Encounter : encounter
Observation -- "[0..1]" Patient : subject

' ========================================
' end: definition of associations
' ========================================
@enduml
