@startuml
' ========================================
' start: configuration
' ========================================

skinparam linetype ortho

' ========================================
' end: configuration
' ========================================

' ========================================
' start: definition of entities/classes
' ========================================

class Encounter {
}

class Observation {
  identifier : Identifier [0..*]
  category : CodeableConcept [0..*]
  code : CodeableConcept [1..1]
  ...
}

class Patient {
}

' ========================================
' end: definition of entities/classes
' ========================================

' ========================================
' start: definition of associations
' ========================================

Observation *-- "[0..*]" Component : component
Observation *-- "[0..*]" ReferenceRange : referenceRange
Component *-- "[0..*]" ReferenceRange : referenceRange
Observation *-- "[0..1]" Encounter : encounter
Observation *-- "[0..1]" Patient : subject

' ========================================
' end: definition of associations
' ========================================
@enduml
