@startuml
' ========================================
' start: configuration
' ========================================

skinparam linetype ortho

' ========================================
' end: configuration
' ========================================

' ========================================
' start: definition of entities/classes
' ========================================

class Patient {
}

class RelatedPerson {
}

class Encounter {
}

class Observation {
}

class ObservationDefinition {
}

class QualifiedInterval {
}

class Questionnaire {
}

class QuestionnaireItem {
}

class QuestionnaireResponseItem {
}

class ValueSet {
}

' ========================================
' end: definition of entities/classes
' ========================================

' ========================================
' start: definition of notes
' ========================================


' ========================================
' end: definition of notes
' ========================================


' ========================================
' start: definition of associations
' ========================================

Questionnaire *-- "[0..*]" QuestionnaireItem : item
QuestionnaireItem *-- "[0..*]" QuestionnaireItem : item
QuestionnaireItem -l- "[0..1]" ValueSet : answerValueSet


QuestionnaireResponse -- "[0..1]" Questionnaire : questionnaire
QuestionnaireResponse -- "[0..1]" Patient : subject
QuestionnaireResponse -- "[0..1]" Patient : source
QuestionnaireResponse -- "[0..1]" Practitioner : source
QuestionnaireResponse -- "[0..1]" Encounter : encounter
QuestionnaireResponse *-- "[0..*]" QuestionnaireResponseItem : item
QuestionnaireResponseItem *-- "[0..*]" QuestionnaireResponseItem : item
QuestionnaireResponseItem -- "[1..1]" QuestionnaireItem : linkId
QuestionnaireResponseItem *-- "[0..*]" Answer : answer
Answer *-- "[0..*]" QuestionnaireResponseItem : item

Encounter -- "[0..1]" Patient: subject

Observation -- "[0..1]" Patient: subject
Observation -- "[0..1]" Encounter: encounter
Observation -- "[0..*]" QuestionnaireResponse: derivedFrom
Observation *-- "[0..*]" RelatedPerson : performer
Observation *-- "[0..*]" Practitioner : performer

ObservationDefinition *-- "[0..*]" QualifiedInterval : qualifiedInterval
ObservationDefinition -- "[0..1]" ValueSet : validCodedValueSet
ObservationDefinition -- "[0..1]" ValueSet : normalCodedValueSet
ObservationDefinition -- "[0..1]" ValueSet : abnormalCodedValueSet
ObservationDefinition -- "[0..1]" ValueSet : criticalCodedValueSet
Observation -- "[0..*]" ObservationDefinition : instantiates

RelatedPerson *-- "[1..1]" Patient : patient

' ========================================
' end: definition of associations
' ========================================
@enduml

