@startuml
' ========================================
' start: configuration
' ========================================

skinparam linetype ortho

' ========================================
' end: configuration
' ========================================

' ========================================
' start: definition of entities/classes
' ========================================

'class Contact {
'  relationship : CodeableConcept [0..*] « PatientContactRelationship+ »
'  name : HumanName [0..1]
'  telecom : ContactPoint [0..*]
'  address : Address [0..1]
'  gender : code [0..1] « AdministrativeGender! »
'  organization : Reference [0..1] « Organization »
'  period : Period [0..1]
'}

'class Communication {
'  language : CodeableConcept [1..1] « CommonLanguages? »
'  preferred : boolean [0..1]
'}

class Link {
  other : Reference [1..1] « Patient|RelatedPerson »
'  type : code [1..1] « LinkType! »
}

class Patient {
  identifier : Identifier [0..*]
  active : boolean [0..1]
'  name : HumanName [0..*]
'  telecom : ContactPoint [0..*]
  gender (sex) : code [0..1] « AdministrativeGender! »
  birthDate (yearOfBirth) : date [0..1]
  (education) : NewEducationResource
'  (ethnicity) : NewEthnicityResource --> Observation
  (household) : NewHouseholdResource
'  deceased[x] : Type [0..1] « boolean|dateTime »
  address (zipCode) : Address [0..*]
'  maritalStatus : CodeableConcept [0..1] « Marital Status + »
'  multipleBirth[x] : Type [0..1] « boolean|integer »
'  photo : Attachment [0..*]
'  generalPractitioner : Reference [0..*] « Organization|Practitioner|PractitionerRole »
'  managingOrganization : Reference [0..1] « Organization »
}

' ========================================
' end: definition of entities/classes
' ========================================

' ========================================
' start: definition of associations
' ========================================

Patient *-r- "[0..*]" Link : link
'Patient *-- "[0..*]" Contact : contact
'Patient *-- "[0..*]" Communication : communication

' ========================================
' end: definition of associations
' ========================================

' ========================================
' start: definition of notes
' ========================================

note right of Patient::gender (sex)
  This is, literally, the biological patient's sex, and not how (s)he considers to be her/his gender.
end note

' ========================================
' end: definition of notes
' ========================================
@enduml
