@startuml
' ========================================
' start: configuration
' ========================================

skinparam linetype ortho

' ========================================
' end: configuration
' ========================================

' ========================================
' start: definition of entities/classes
' ========================================

class Practitioner {
  identifier : Identifier [0..*]
  active : boolean [0..1]
}

' ========================================
' end: definition of entities/classes
' ========================================

' ========================================
' start: definition of associations
' ========================================

' ========================================
' end: definition of associations
' ========================================
@enduml
