@startuml
' ========================================
' start: configuration
' ========================================

skinparam linetype ortho

' ========================================
' end: configuration
' ========================================

' ========================================
' start: definition of entities/classes
' ========================================

class Questionnaire {
  url : uri [0..1]
  identifier : Identifier [0..*]
  version : string [0..1]
  name : string [0..1]
  title : string [0..1]
  status : code [1..1] « draft | active | retired | unknown »
  date : dateTime [0..1]
  description : markdown [0..1]
  code : Coding [0..*]
}

class QuestionnaireResponse {
  identifier : Identifier [0..*]
  status : code [1..1] « in-progress | completed | amended | entered-in-error | stopped »
  authored : dateTime [0..1]
}


class QuestionnaireItem {
  linkId : string [1..1]
  code : Coding [0..*]
  text : string [0..1]
  type : code [1..1]
  enableBehavior : code [0..1] « all | any »
  required : boolean [0..1]
  repeats : boolean [0..1]
  itemControl : Extension questionnaire-itemControl [0..1]
  minValue : Extension minValue [0..1]
  maxValue : Extension maxValue [0..1]
  unit : Extension questionnaire-unit [0..1]
}


class QuestionnaireResponseItem {
  text : string [0..1]
}

class ValueSet {
  }

class Patient {
  }
  
class Practitioner {
  }

class Encounter {
  }

class AnswerOption {
  valueX : Type [1..1] « integer | date | ... »
  initialSelected : boolean [0..1]
  optionPrefix : Extension questionnaire-optionPrefix [0..1]  
}
 
class Initial {
  valueX : Type [1..1] « integer | date | ... »
}

class Answer {
  valueX : Type [1..1] « integer | date | ... »
}

class EnableWhen {
  operator : code [1..1] « exists | = | != | > | < | >= | <= »
  answerX : Type [1..1] « integer | date | ... »
}

' ========================================
' end: definition of entities/classes
' ========================================

' ========================================
' start: definition of notes
' ========================================

note right of QuestionnaireItem::itemControl
  predefined FHIR extension http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl
end note

note right of QuestionnaireItem::minValue
  predefined FHIR extension http://hl7.org/fhir/StructureDefinition/minValue
end note

note right of QuestionnaireItem::maxValue
  predefined FHIR extension http://hl7.org/fhir/StructureDefinition/maxValue
end note

note right of QuestionnaireItem::unit
  predefined FHIR extension http://hl7.org/fhir/StructureDefinition/questionnaire-unit
end note

note bottom of AnswerOption
  predefined FHIR extension http://hl7.org/fhir/StructureDefinition/questionnaire-optionPrefix
end note

' ========================================
' end: definition of notes
' ========================================


' ========================================
' start: definition of associations
' ========================================

Questionnaire *-- "[0..*]" QuestionnaireItem : item
QuestionnaireItem *-- "[0..*]" QuestionnaireItem : item
QuestionnaireItem *-- "[0..*]" Initial : initial
QuestionnaireItem *-- "[0..*]" AnswerOption : answerOption
QuestionnaireItem *-- "[0..*]" EnableWhen : enableWhen
EnableWhen -- "[1..1]" QuestionnaireItem : question
QuestionnaireItem -- "[0..1]" ValueSet : answerValueSet


QuestionnaireResponse *-- "[1..1]" Questionnaire : questionnaire
QuestionnaireResponse *-- "[0..*]" QuestionnaireResponseItem : item
QuestionnaireResponse -- "[0..1]" Patient : subject
QuestionnaireResponse -- "[0..1]" Patient : source
QuestionnaireResponse -- "[0..1]" Practitioner : source
QuestionnaireResponse -- "[0..1]" Encounter : encounter
QuestionnaireResponseItem *-- "[0..*]" QuestionnaireResponseItem : item
QuestionnaireResponseItem -- "[1..1]" QuestionnaireItem : linkId
QuestionnaireResponseItem *-- "[0..*]" Answer : answer
Answer *-- "[0..*]" QuestionnaireResponseItem : item

' ========================================
' end: definition of associations
' ========================================
@enduml
